name: 'Hello World'
description: 'Greet someone'
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: install license-checker library
      run: npm install -g license-checker
      shell: bash  
    - run: license-checker --production  --json > ${{ github.action_path }}/license-used.json
      shell: bash  
    - run: cat  ${{ github.action_path }}/license-used.json 
      shell: bash
    - name: run validation script
      run: node ${{ github.action_path }}/license-check.js
      shell: bash

