name: 'validate packages license'
description: 'validate packages license against list of invalid licenses list'
inputs:
  ignore-packages:
    description: 'List of packages that should be ignored for validation license check. Syntax: package@version separated by semi-colon'
    default: ''
runs:
  using: "composite"
  steps:
    - name: install license-checker library
      run: npm install -g license-checker
      shell: bash  
    - name: get all packages license info as json
      run: license-checker --production --excludePackages '${{ inputs.ignore-packages }}'  --json > ${{ github.action_path }}/license-used.json
      shell: bash  
    - name: run validation script
      run: node ${{ github.action_path }}/license-check.js
      shell: bash

