name: check-licenses

on:
  workflow_dispatch:

jobs:
  check-licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
          registry-url: https://registry.npmjs.org
      - run: yarn install --frozen-lockfile --ignore-scripts
      - uses: ./.github/actions/license-check
        with:
          ignore-packages: '@forge/util@1.3.3'
